namespace :restaurants do

  desc 'Augment restaurants with tags'
  task :augment_tags, [] => :environment do
    add_tags(Restaurant.find(1), 'Hamburger', 'Fast Food')
    add_tags(Restaurant.find(2), 'Hamburger', 'American')
    add_tags(Restaurant.find(3), 'Homemade', 'Meat')
    add_tags(Restaurant.find(4), 'Sandwich')
    add_tags(Restaurant.find(5), 'Cafe')
    add_tags(Restaurant.find(6), 'Asian')
    add_tags(Restaurant.find(8), 'Pizzeria')
    add_tags(Restaurant.find(11), 'Salad')
    add_tags(Restaurant.find(12), 'Homemade', 'Fast Food', 'Middle Eastern')
    add_tags(Restaurant.find(14), 'Asian')
    add_tags(Restaurant.find(16), 'Meat')
    add_tags(Restaurant.find(21), 'Homemade')
    add_tags(Restaurant.find(22), 'Asian')
    add_tags(Restaurant.find(23), 'Homemade', 'Middle Eastern')
    add_tags(Restaurant.find(24), 'Middle Eastern')
    add_tags(Restaurant.find(25), 'Sandwich', 'Salad')
    add_tags(Restaurant.find(26), 'Grill')
    add_tags(Restaurant.find(27), 'Sushi', 'Japanese')
    add_tags(Restaurant.find(31), 'Pizzeria')
    add_tags(Restaurant.find(32), 'Hamburger')
    add_tags(Restaurant.find(33), 'Sushi', 'Japanese')
    add_tags(Restaurant.find(34), 'Sushi', 'Japanese')
    add_tags(Restaurant.find(35), 'Meat')
    add_tags(Restaurant.find(36), 'Asian')
    add_tags(Restaurant.find(37), 'Pizzeria')
    add_tags(Restaurant.find(38), 'American')
    add_tags(Restaurant.find(41), 'Homemade')
    add_tags(Restaurant.find(43), 'Pizzeria')
    add_tags(Restaurant.find(44), 'Middle Eastern', 'Homemade')
    add_tags(Restaurant.find(45), 'Homemade')
    add_tags(Restaurant.find(46), 'Bistro')
    add_tags(Restaurant.find(48), 'Salad', 'Sandwich')
    add_tags(Restaurant.find(49), 'Pizzeria', 'Fast Food')
    add_tags(Restaurant.find(50), 'Thai Food', 'Fast Food')
    add_tags(Restaurant.find(51), 'Fast Food')
    add_tags(Restaurant.find(52), 'Conditure')
    add_tags(Restaurant.find(56), 'Pizzeria', 'Fast Food')
    add_tags(Restaurant.find(57), 'Cafe')
    add_tags(Restaurant.find(59), 'Cafe', 'Healthy')
    add_tags(Restaurant.find(60), 'Hamburger')
    add_tags(Restaurant.find(61), 'Hummus')
    add_tags(Restaurant.find(64), 'Italian')
    add_tags(Restaurant.find(66), 'Homemade')
    add_tags(Restaurant.find(68), 'Asian')
    add_tags(Restaurant.find(69), 'Italian')
    add_tags(Restaurant.find(70), 'Meat', 'Fast Food')
    add_tags(Restaurant.find(73), 'Italian')
    add_tags(Restaurant.find(74), 'Middle Eastern', 'Vegetarian')
    add_tags(Restaurant.find(76), 'Middle Eastern', 'Homemade')
    add_tags(Restaurant.find(79), 'Italian')
    add_tags(Restaurant.find(80), 'Asian')
    add_tags(Restaurant.find(81), 'Pizzeria', 'Fast Food')
    add_tags(Restaurant.find(83), 'Asian', 'Dim Sum')
    add_tags(Restaurant.find(85), 'Sandwich', 'Fast Food')
    add_tags(Restaurant.find(89), 'Thai Food', 'Asian')
    add_tags(Restaurant.find(91), 'Pizzeria', 'Fast Food')
    add_tags(Restaurant.find(92), 'Conditure', 'Ice Cream')
    add_tags(Restaurant.find(93), 'Italian')
    add_tags(Restaurant.find(96), 'Pizzeria')
    add_tags(Restaurant.find(97), 'Meat')
    add_tags(Restaurant.find(98), 'Homemade')
  end

  def add_tags(restaurant, *tags)
    tags.each do |tag|
      restaurant.tags.where(:quantity => 1, :tag_definition_id => TagDefinition.find_by_name(tag).id).first_or_create
    end
  end

end