defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: lunchtime_development
  host: localhost
  pool: 5

development: *defaults

test:
  <<: *defaults
  database: lunchtime_test

production:
  <<: *defaults
  database: lunchtime_production

