defaults: &defaults
  adapter: mysql2
  username: root
  password: hello
  encoding: utf8
  database: lunchtime

development: *defaults

test:
  <<: *defaults
  database: lunchtime_test

production: *defaults

